/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 새로운 사용자를 등록합니다. 이메일은 중복될 수 없습니다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일과 비밀번호로 로그인하여 JWT 토큰을 발급받습니다. 발급받은 토큰은 인증이 필요한 API 호출 시 Authorization 헤더에 포함해야 합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrollments/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 배치 수강 신청 🔒
         * @description 여러 강의를 한 번에 수강 신청합니다. **인증이 필요합니다.**
         *
         *     ### 특징
         *     - **부분 성공 지원**: 일부 강의만 성공하더라도 해당 강의들은 수강 신청됩니다.
         *     - 성공/실패한 강의 목록이 각각 반환됩니다.
         *
         *     ### 응답 구조
         *     ```json
         *     {
         *       "success": [
         *         { "enrollmentId": 1, "courseId": 1, "courseTitle": "강의1" }
         *       ],
         *       "failed": [
         *         { "courseId": 2, "reason": "이미 수강 신청한 강의입니다" }
         *       ]
         *     }
         *     ```
         */
        post: operations["enrollBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 강의 목록 조회
         * @description 등록된 모든 강의 목록을 조회합니다. 인증 없이 호출할 수 있습니다. 페이지네이션과 정렬을 지원합니다.
         */
        get: operations["getAllCourses"];
        put?: never;
        /**
         * 강의 등록 🔒
         * @description 새로운 강의를 등록합니다. **강사(INSTRUCTOR) 권한이 필요합니다.** (Authorization 헤더에 Bearer 토큰 필요)
         */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수강 신청 🔒
         * @description 강의에 수강 신청합니다. **인증이 필요합니다.**
         *
         *     ### 사용 방법
         *     1. 먼저 로그인 API를 호출하여 JWT 토큰을 발급받으세요.
         *     2. 우측 상단의 **Authorize** 버튼을 클릭하세요.
         *     3. 발급받은 토큰을 입력하세요 (Bearer 제외).
         *     4. 수강하려는 강의의 ID를 입력하고 실행하세요.
         *
         *     ### 주의사항
         *     - 이미 수강 신청한 강의는 다시 신청할 수 없습니다.
         *     - 정원이 가득 찬 강의는 수강 신청할 수 없습니다.
         */
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 강의 상세 조회
         * @description 특정 강의의 상세 정보를 조회합니다. 인증 없이 호출할 수 있습니다.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 회원가입 요청 */
        SignupRequest: {
            /**
             * @description 이메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호 (6~10자, 영문+숫자 조합)
             * @example Pass1234
             */
            password: string;
            /**
             * @description 사용자 이름
             * @example 홍길동
             */
            name: string;
            /**
             * @description 휴대폰 번호
             * @example 010-1234-5678
             */
            phone: string;
            /**
             * @description 회원 유형
             * @example STUDENT
             * @enum {string}
             */
            role: "STUDENT" | "INSTRUCTOR";
        };
        /** @description 회원가입 응답 */
        SignupResponse: {
            /**
             * Format: int64
             * @description 생성된 사용자 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 휴대폰 번호
             * @example 010-1234-5678
             */
            phone?: string;
            /**
             * @description 회원 유형
             * @example STUDENT
             * @enum {string}
             */
            role?: "STUDENT" | "INSTRUCTOR";
            /**
             * @description 결과 메시지
             * @example 회원가입이 완료되었습니다
             */
            message?: string;
        };
        /** @description 에러 응답 */
        ErrorResponse: {
            /**
             * @description 에러 코드
             * @example U001
             */
            code?: string;
            /**
             * @description 에러 메시지
             * @example 이미 사용 중인 이메일입니다
             */
            message?: string;
            /**
             * Format: date-time
             * @description 발생 시각
             */
            timestamp?: string;
        };
        /** @description 로그인 요청 */
        LoginRequest: {
            /**
             * @description 이메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        /** @description 로그인 응답 */
        LoginResponse: {
            /**
             * @description JWT 액세스 토큰
             * @example eyJhbGciOiJIUzUxMiJ9...
             */
            accessToken?: string;
            /**
             * @description 토큰 타입
             * @example Bearer
             */
            tokenType?: string;
            user?: components["schemas"]["UserInfo"];
        };
        /** @description 사용자 정보 */
        UserInfo: {
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 이름
             * @example 홍길동
             */
            name?: string;
            /**
             * @description 휴대폰 번호
             * @example 010-1234-5678
             */
            phone?: string;
            /**
             * @description 회원 유형
             * @example STUDENT
             * @enum {string}
             */
            role?: "STUDENT" | "INSTRUCTOR";
        };
        /** @description 배치 수강 신청 요청 */
        BatchRequest: {
            /**
             * @description 수강 신청할 강의 ID 목록
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            courseIds: number[];
        };
        /** @description 배치 수강 신청 응답 (부분 성공 지원) */
        BatchResponse: {
            /** @description 성공한 수강 신청 목록 */
            success?: components["schemas"]["SuccessItem"][];
            /** @description 실패한 수강 신청 목록 */
            failed?: components["schemas"]["FailedItem"][];
        };
        /** @description 배치 수강 신청 실패 항목 */
        FailedItem: {
            /**
             * Format: int64
             * @description 강의 ID
             * @example 3
             */
            courseId?: number;
            /**
             * @description 실패 사유
             * @example 이미 수강 신청한 강의입니다
             */
            reason?: string;
        };
        /** @description 배치 수강 신청 성공 항목 */
        SuccessItem: {
            /**
             * Format: int64
             * @description 수강 신청 ID
             * @example 1
             */
            enrollmentId?: number;
            /**
             * Format: int64
             * @description 강의 ID
             * @example 1
             */
            courseId?: number;
            /**
             * @description 강의 제목
             * @example 부동산 투자 기초
             */
            courseTitle?: string;
        };
        /** @description 강의 등록 요청 */
        CreateRequest: {
            /**
             * @description 강의 제목
             * @example React 기초 마스터
             */
            title: string;
            /**
             * @description 강의 설명
             * @example React의 기본 개념부터 Hooks까지 배웁니다.
             */
            description?: string;
            /**
             * @description 강사 이름
             * @example 김강사
             */
            instructorName: string;
            /**
             * Format: int32
             * @description 최대 수강 인원
             * @example 30
             */
            maxStudents: number;
            /**
             * Format: int32
             * @description 수강료 (원)
             * @example 100000
             */
            price: number;
        };
        /** @description 강의 상세 응답 */
        Response: {
            /**
             * Format: int64
             * @description 강의 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 강의 제목
             * @example 부동산 투자 기초
             */
            title?: string;
            /**
             * @description 강의 설명
             * @example 부동산 투자의 기본 개념과 전략을 배웁니다.
             */
            description?: string;
            /**
             * @description 강사 이름
             * @example 김투자
             */
            instructorName?: string;
            /**
             * Format: int32
             * @description 최대 수강 인원
             * @example 30
             */
            maxStudents?: number;
            /**
             * Format: int32
             * @description 현재 수강 인원
             * @example 5
             */
            currentStudents?: number;
            /**
             * Format: int32
             * @description 남은 자리
             * @example 25
             */
            availableSeats?: number;
            /**
             * @description 정원 마감 여부
             * @example false
             */
            isFull?: boolean;
            /**
             * Format: int32
             * @description 수강료 (원)
             * @example 100000
             */
            price?: number;
            /**
             * Format: date-time
             * @description 강의 등록일시
             */
            createdAt?: string;
        };
        Page: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: Record<string, never>[];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            paged?: boolean;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SignupResponse"];
                };
            };
            /** @description 잘못된 요청 (유효성 검증 실패) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "G001",
                     *       "message": "이메일은 필수입니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이메일 중복 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "U001",
                     *       "message": "이미 사용 중인 이메일입니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 비밀번호 불일치 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "U003",
                     *       "message": "비밀번호가 일치하지 않습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 사용자 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "U002",
                     *       "message": "사용자를 찾을 수 없습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    enrollBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description 배치 수강 신청 처리 완료 (부분 성공 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BatchResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "G001",
                     *       "message": "강의 ID 목록은 필수입니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "A003",
                     *       "message": "인증이 필요합니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllCourses: {
        parameters: {
            query?: {
                /**
                 * @description 페이지 번호 (0부터 시작)
                 * @example 0
                 */
                page?: number;
                /**
                 * @description 페이지 크기
                 * @example 10
                 */
                size?: number;
                /**
                 * @description 정렬 기준: recent (최신순), popular (신청자 많은 순), rate (신청률 높은 순)
                 * @example recent
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Page"];
                };
            };
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description 강의 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Response"];
                };
            };
            /** @description 잘못된 요청 (유효성 검증 실패) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "G001",
                     *       "message": "강의 제목은 필수입니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "A003",
                     *       "message": "인증이 필요합니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 강사만 등록 가능 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "C003",
                     *       "message": "강사만 강의를 등록할 수 있습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 강의 ID
                 * @example 1
                 */
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 수강 신청 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Response"];
                };
            };
            /** @description 정원 초과 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "C002",
                     *       "message": "수강 정원이 초과되었습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 필요 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "A003",
                     *       "message": "인증이 필요합니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 강의 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "C001",
                     *       "message": "강의를 찾을 수 없습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 수강 신청함 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "E001",
                     *       "message": "이미 수강 신청한 강의입니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 강의 ID
                 * @example 1
                 */
                courseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Response"];
                };
            };
            /** @description 강의 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "C001",
                     *       "message": "강의를 찾을 수 없습니다",
                     *       "timestamp": "2024-01-15T14:30:00"
                     *     }
                     */
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
